"""Shell integration script generation."""
from pathlib import Path

SUPPORTED_SHELLS = ["fish", "bash", "zsh"]


def get_completion_path(shell: str) -> Path:
    """Get the default installation path for completion scripts.

    Args:
        shell: Shell name (bash, zsh, fish).

    Returns:
        Path where completion script should be installed.

    Raises:
        ValueError: If shell is not supported.
    """
    home = Path.home()

    if shell == "bash":
        return home / ".bash_completion.d" / "dirq"
    elif shell == "zsh":
        return home / ".zsh" / "completions" / "_dirq"
    elif shell == "fish":
        return home / ".config" / "fish" / "completions" / "dirq.fish"
    else:
        raise ValueError(f"Unsupported shell: {shell}. Must be one of: bash, zsh, fish")


def get_wrapper_path(shell: str) -> Path:
    """Get the default installation path for wrapper function.

    Args:
        shell: Shell name (bash, zsh, fish).

    Returns:
        Path where wrapper function should be installed.

    Raises:
        ValueError: If shell is not supported.
    """
    home = Path.home()

    if shell == "bash":
        return home / ".bash_completion.d" / "dirq-wrapper"
    elif shell == "zsh":
        return home / ".zsh" / "functions" / "dirq-wrapper"
    elif shell == "fish":
        return home / ".config" / "fish" / "functions" / "dirq.fish"
    else:
        raise ValueError(f"Unsupported shell: {shell}. Must be one of: bash, zsh, fish")


def generate_shell_script(shell_type: str) -> str:
    """
    Generate shell-specific integration script.

    The script includes:
    - A wrapper function that calls dirq navigate and changes directory
    - Static completion definitions for subcommands and flags

    Args:
        shell_type: Type of shell (fish, bash, or zsh).

    Returns:
        Shell script as a string.

    Raises:
        ValueError: If shell_type is not supported.
    """
    if shell_type not in SUPPORTED_SHELLS:
        raise ValueError(
            f"error: unsupported shell '{shell_type}'. "
            f"Supported: {', '.join(SUPPORTED_SHELLS)}"
        )

    if shell_type == "fish":
        return _generate_fish_script()
    elif shell_type == "bash":
        return _generate_bash_script()
    elif shell_type == "zsh":
        return _generate_zsh_script()

    raise ValueError(f"error: unsupported shell '{shell_type}'")


def _generate_fish_wrapper() -> str:
    """Generate Fish shell wrapper function."""
    return '''# dirq shell wrapper function for Fish
# Generated by dirq init shell fish

function dirq --description "dirq wrapper with automatic directory change"
    if test "$argv[1]" = "navigate"
        set -l selected (command dirq navigate $argv[2..-1])
        if test $status -eq 0
            cd "$selected"
        end
    else
        command dirq $argv
    end
    commandline -f repaint
end
'''


def _generate_fish_completion() -> str:
    """Generate Fish shell completion script."""
    return '''# Fish completion for dirq
# Generated by dirq init shell fish

# Disable file completions for all commands
complete -c dirq -f

# Main commands
complete -c dirq -n "__fish_use_subcommand" -a "navigate" -d "Navigate to a bookmarked folder"
complete -c dirq -n "__fish_use_subcommand" -a "save" -d "Save a folder bookmark"
complete -c dirq -n "__fish_use_subcommand" -a "delete" -d "Delete a bookmark"
complete -c dirq -n "__fish_use_subcommand" -a "init" -d "Initialize config or shell integration"

# Navigate completions
complete -c dirq -n "__fish_seen_subcommand_from navigate" -l "only" -d "Include only specified bookmarks"
complete -c dirq -n "__fish_seen_subcommand_from navigate" -l "except" -d "Exclude specified bookmarks"

# Init subcommands
complete -c dirq -n '__fish_seen_subcommand_from init; and not __fish_seen_subcommand_from config shell' -a config -d 'Create default config file'
complete -c dirq -n '__fish_seen_subcommand_from init; and not __fish_seen_subcommand_from config shell' -a shell -d 'Install shell integration'

# Init shell completions
complete -c dirq -n '__fish_seen_subcommand_from init; and __fish_seen_subcommand_from shell' -a 'bash zsh fish'
'''


def _generate_fish_script() -> str:
    """Generate Fish shell integration script."""
    wrapper = _generate_fish_wrapper()
    completion = _generate_fish_completion()
    return f'''# dirq shell integration for Fish
# Add this to your ~/.config/fish/config.fish:
# source (dirq init shell fish | psub)

{wrapper.strip()}

{completion.strip()}
'''


def _generate_bash_wrapper() -> str:
    """Generate Bash shell wrapper function."""
    return '''# dirq shell wrapper function for Bash
# Generated by dirq init shell bash

dirq() {
    if [ "$1" = "navigate" ]; then
        local selected
        selected=$(command dirq navigate "${@:2}")
        if [ $? -eq 0 ]; then
            cd "$selected" || return
        fi
    else
        command dirq "$@"
    fi
}
'''


def _generate_bash_completion() -> str:
    """Generate Bash shell completion script."""
    return '''# Bash completion for dirq
# Generated by dirq init shell bash

_dirq_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local commands="navigate save delete init"

    case "${COMP_CWORD}" in
        1)
            COMPREPLY=( $(compgen -W "${commands}" -- "${cur}") )
            return 0
            ;;
    esac

    case "${prev}" in
        navigate)
            COMPREPLY=( $(compgen -W "--only --except" -- "${cur}") )
            return 0
            ;;
        init)
            COMPREPLY=( $(compgen -W "config shell" -- "${cur}") )
            return 0
            ;;
        shell)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "${cur}") )
            return 0
            ;;
    esac

    return 0
}

complete -F _dirq_completions dirq
'''


def _generate_bash_script() -> str:
    """Generate Bash shell integration script."""
    wrapper = _generate_bash_wrapper()
    completion = _generate_bash_completion()
    return f'''# dirq shell integration for Bash
# Add this to your ~/.bashrc:
# eval "$(dirq init shell bash)"

{wrapper.strip()}

{completion.strip()}
'''


def _generate_zsh_wrapper() -> str:
    """Generate Zsh shell wrapper function."""
    return '''# dirq shell wrapper function for Zsh
# Generated by dirq init shell zsh

dirq() {
    if [[ "$1" == "navigate" ]]; then
        local selected
        selected=$(command dirq navigate "${@:2}")
        if [[ $? -eq 0 ]]; then
            cd "$selected" || return
        fi
    else
        command dirq "$@"
    fi
}
'''


def _generate_zsh_completion() -> str:
    """Generate Zsh shell completion script."""
    return '''#compdef dirq
# Zsh completion for dirq
# Generated by dirq init shell zsh

_dirq() {
    local -a commands
    commands=(
        'navigate:Navigate to a bookmarked folder'
        'save:Save a folder bookmark'
        'delete:Delete a bookmark'
        'init:Initialize config or shell integration'
    )

    local -a init_commands
    init_commands=(
        'config:Create default configuration file'
        'shell:Install shell integration'
    )

    local -a shells
    shells=(bash zsh fish)

    _arguments -C \\
        '1: :->command' \\
        '*: :->args' \\
        && return 0

    case $state in
        command)
            _describe -t commands 'dirq command' commands
            ;;
        args)
            case $words[2] in
                navigate)
                    _arguments \\
                        '--only[Include only specified bookmarks]' \\
                        '--except[Exclude specified bookmarks]'
                    ;;
                init)
                    case $words[3] in
                        shell)
                            _describe -t shells 'shell' shells
                            ;;
                        *)
                            _describe -t init_commands 'init command' init_commands
                            ;;
                    esac
                    ;;
            esac
            ;;
    esac
}

_dirq "$@"
'''


def _generate_zsh_script() -> str:
    """Generate Zsh shell integration script."""
    wrapper = _generate_zsh_wrapper()
    completion = _generate_zsh_completion()
    return f'''# dirq shell integration for Zsh
# Add this to your ~/.zshrc:
# eval "$(dirq init shell zsh)"

{wrapper.strip()}

{completion.strip()}
'''


def install_completion(shell: str) -> Path:
    """Install completion script for specified shell.

    Args:
        shell: Shell name (bash, zsh, fish).

    Returns:
        Path where script was installed.

    Raises:
        ValueError: If shell is not supported.
        OSError: If installation fails.
    """
    path = get_completion_path(shell)

    if shell == "bash":
        script = _generate_bash_completion()
    elif shell == "zsh":
        script = _generate_zsh_completion()
    elif shell == "fish":
        script = _generate_fish_completion()
    else:
        raise ValueError(f"Unsupported shell: {shell}. Must be one of: bash, zsh, fish")

    # Ensure parent directory exists
    path.parent.mkdir(parents=True, exist_ok=True)

    # Write script
    path.write_text(script)

    return path


def install_wrapper(shell: str) -> Path:
    """Install wrapper function for specified shell.

    Args:
        shell: Shell name (bash, zsh, fish).

    Returns:
        Path where wrapper was installed.

    Raises:
        ValueError: If shell is not supported.
        OSError: If installation fails.
    """
    path = get_wrapper_path(shell)

    if shell == "bash":
        script = _generate_bash_wrapper()
    elif shell == "zsh":
        script = _generate_zsh_wrapper()
    elif shell == "fish":
        script = _generate_fish_wrapper()
    else:
        raise ValueError(f"Unsupported shell: {shell}. Must be one of: bash, zsh, fish")

    # Ensure parent directory exists
    path.parent.mkdir(parents=True, exist_ok=True)

    # Write script
    path.write_text(script)

    return path


def get_installation_instructions(
    shell: str,
    completion_path: Path,
    wrapper_path: Path,
) -> str:
    """Get instructions for activating completion and wrapper after installation.

    Args:
        shell: Shell name.
        completion_path: Path where completion was installed.
        wrapper_path: Path where wrapper was installed.

    Returns:
        Human-readable activation instructions.
    """
    if shell == "bash":
        return (
            f"Installed bash completion: {completion_path}\n"
            f"Installed bash wrapper: {wrapper_path}\n"
            f"\nTo activate, add to ~/.bashrc:\n"
            f"  source {completion_path}\n"
            f"  source {wrapper_path}\n"
            f"\nThen restart your shell or run: source ~/.bashrc"
        )
    elif shell == "zsh":
        return (
            f"Installed zsh completion: {completion_path}\n"
            f"Installed zsh wrapper: {wrapper_path}\n"
            f"\nTo activate, add to ~/.zshrc:\n"
            f"  fpath=(~/.zsh/completions $fpath)\n"
            f"  autoload -Uz compinit && compinit\n"
            f"  source {wrapper_path}\n"
            f"\nThen restart your shell."
        )
    elif shell == "fish":
        return (
            f"Installed fish completion: {completion_path}\n"
            f"Installed fish wrapper: {wrapper_path}\n"
            f"\nFish will automatically load these files.\n"
            f"Restart fish shell or run: exec fish"
        )
    else:
        return (
            f"Installed completion: {completion_path}\n"
            f"Installed wrapper: {wrapper_path}"
        )

